version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: Library@123
    ports:
      - "3307:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
